---
- name: Playbook to run Smoke Test of 3-Tier app on OSP
  hosts: workstation
  gather_facts: false
  tasks:
  - name: Get OpenStack servers inventory
    os_server_facts:
     cloud: openstack
     server: 'frontend'
    register: openstack_info
    tags:
      - osp.smoke

  - name: debug frontend cfg
    shell: cat /etc/haproxy/haproxy.cfg
    with_items:
      - "{{ openstack_info.ansible_facts.openstack_servers }}"
    register: ha_config

  - name: show debug output
    debug:
      msg: "{{ ha_config }}"

  - name: Curl website
    uri:
     url: "http://{{item.public_v4}}"
     return_content: yes
    with_items:
      - "{{ openstack_info.ansible_facts.openstack_servers }}"
    register: webpage
    tags:
      - osp.smoke

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in webpage.results[0].content"
    tags:
      - osp.smoke
