---
#Tasks for site-install-isolated-node.yaml
- name: Append inventory file
  blockinfile:
    path: /root/ansible-tower-setup-latest/inventory
    block: |
      [isolated_group_osp]
      workstation-{{OSP_GUID}}.{{OSP_DOMAIN}}
      [isolated_group_osp:vars]
      controller=tower
      ansible_user='cloud-user'
      ansible_ssh_private_key_file='~/.ssh/openstack.pem'
      ansible_ssh_common_args='-o StrictHostKeyChecking=no'
    state: present
- name: Run Ansible Tower setup
  shell: /root/ansible-tower-setup-latest/setup.sh
  async: 3600
  poll: 36
