---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: add repos
  template:
    src: templates/repos_template.j2
    dest: /etc/yum.repos.d/homework.repo
    owner: root
    group: root
    mode: '0644'

- name: enable repos
  shell: yum-config-manager --enable homweork\*
 
- name: install base tools and packages
  yum:
    name: 
      - python-pip
      - gcc
    state: latest
